apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planner-lbl
  template:
    metadata:
      labels:
        app: planner-lbl
    spec:
      containers:
        - name: planner-container
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-prod
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env-prod
          image: husseinatdocker/planner-app:133
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: planner-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: planner-lbl
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: planner-data-pv
  labels:
    app: planner-db-lbl
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: planner-db-lbl
  name: planner-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planner-db-lbl
  name: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planner-db-lbl
  template:
    metadata:
      labels:
        app: planner-db-lbl
    spec:
      containers:
        - image: mongo
          name: database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: planner-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: planner-db-lbl
  name: mongo-database-svc
spec:
  # type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      # nodePort: 32700
  selector:
    app: planner-db-lbl
