apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planner-db-lbl
  name: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planner-db-lbl
  template:
    metadata:
      labels:
        app: planner-db-lbl
    spec:
      containers:
        - image: mongo
          name: database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: planner-data-pvc
