apiVersion: v1
kind: PersistentVolume
metadata:
  name: planner-data-pv
  labels:
    app: planner-db-lbl
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
