apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: planner-db-lbl
  name: planner-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
